### ISSUE TITLE
Error opening server

### ISSUE THREAD

**Issue by petruciucur** [brapifra/vscode-phpserver#43]
I receive this error:

Server error: Error: spawn php ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)

Is it any way to solve this ?

**Comment by petruciucur** [comment]
I solved it!
I did not set phpserver.phpPath
Now it is ok. Thanks for this plugin.
